steps:
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/sequences", "."]
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/sequences"]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["run", "deploy", "sequences", "--image", "gcr.io/$PROJECT_ID/sequences", "--region", "us-central1", "--platform", "managed", "--allow-unauthenticated"]
